In [3]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [4]:
df=pd.read_csv('movies_metadata.csv')

In [5]:
df.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [6]:
df.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='object')

In [7]:
df.shape

(45466, 24)

In [8]:
df.isnull().sum()

adult                        0
belongs_to_collection    40972
budget                       0
genres                       0
homepage                 37684
id                           0
imdb_id                     17
original_language           11
original_title               0
overview                   954
popularity                   5
poster_path                386
production_companies         3
production_countries         3
release_date                87
revenue                      6
runtime                    263
spoken_languages             6
status                      87
tagline                  25054
title                        6
video                        6
vote_average                 6
vote_count                   6
dtype: int64

In [9]:
df.drop_duplicates().reset_index(drop=True)

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45448,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...",http://www.imdb.com/title/tt6209470/,439050,tt6209470,fa,رگ خواب,Rising and falling between a man and woman.,...,NaN,0.0,90.0,"[{'iso_639_1': 'fa', 'name': 'فارسی'}]",Released,Rising and falling between a man and woman,Subdue,False,4.0,1.0
45449,False,NaN,0,"[{'id': 18, 'name': 'Drama'}]",NaN,111109,tt2028550,tl,Siglo ng Pagluluwal,An artist struggles to finish his work while a...,...,2011-11-17,0.0,360.0,"[{'iso_639_1': 'tl', 'name': ''}]",Released,NaN,Century of Birthing,False,9.0,3.0
45450,False,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",NaN,67758,tt0303758,en,Betrayal,"When one of her hits goes wrong, a professiona...",...,2003-08-01,0.0,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,A deadly game of wits.,Betrayal,False,3.8,6.0
45451,False,NaN,0,[],NaN,227506,tt0008536,en,Satana likuyushchiy,"In a small town live two brothers, one a minis...",...,1917-10-21,0.0,87.0,[],Released,NaN,Satan Triumphant,False,0.0,0.0
45452,False,NaN,0,[],NaN,461257,tt6980792,en,Queerama,50 years after decriminalisation of homosexual...,...,2017-06-09,0.0,75.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Queerama,False,0.0,0.0

In [10]:
df.duplicated().sum()

np.int64(13)

In [11]:
df.drop_duplicates(inplace=True)

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
df=df[['title','overview','genres','tagline','vote_average','popularity']]

In [14]:
df.head()

,title,overview,genres,tagline,vote_average,popularity
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...","[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",NaN,7.7,21.946943
1,Jumanji,When siblings Judy and Peter discover an encha...,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",Roll the dice and unleash the excitement!,6.9,17.015539
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",Still Yelling. Still Fighting. Still Ready for...,6.5,11.7129
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...","[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",Friends are the people who let you be yourself...,6.1,3.859495
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,"[{'id': 35, 'name': 'Comedy'}]",Just When His World Is Back To Normal... He's ...,5.7,8.387519

In [15]:
df['overview']=df['overview'].fillna('')

In [16]:
df=df.dropna(subset=['title'])

In [17]:
df.iloc[0]['genres']

"[{'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family'}]"

In [18]:
import ast

In [19]:
df['genres']=df['genres'].apply(lambda x :" ".join([i['name'] for i in ast.literal_eval(x)]))

In [20]:
df.head()

,title,overview,genres,tagline,vote_average,popularity
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...",Animation Comedy Family,NaN,7.7,21.946943
1,Jumanji,When siblings Judy and Peter discover an encha...,Adventure Fantasy Family,Roll the dice and unleash the excitement!,6.9,17.015539
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,Romance Comedy,Still Yelling. Still Fighting. Still Ready for...,6.5,11.7129
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",Comedy Drama Romance,Friends are the people who let you be yourself...,6.1,3.859495
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,Comedy,Just When His World Is Back To Normal... He's ...,5.7,8.387519

In [21]:
df['tagline']=df['tagline'].fillna('')

In [22]:
df.isnull().sum()

title           0
overview        0
genres          0
tagline         0
vote_average    0
popularity      0
dtype: int64

In [23]:
df['tags']=df['overview']+" "+df['genres']+" "+df['tagline']

In [24]:
df.head()

,title,overview,genres,tagline,vote_average,popularity,tags
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...",Animation Comedy Family,,7.7,21.946943,"Led by Woody, Andy's toys live happily in his ..."
1,Jumanji,When siblings Judy and Peter discover an encha...,Adventure Fantasy Family,Roll the dice and unleash the excitement!,6.9,17.015539,When siblings Judy and Peter discover an encha...
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,Romance Comedy,Still Yelling. Still Fighting. Still Ready for...,6.5,11.7129,A family wedding reignites the ancient feud be...
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",Comedy Drama Romance,Friends are the people who let you be yourself...,6.1,3.859495,"Cheated on, mistreated and stepped on, the wom..."
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,Comedy,Just When His World Is Back To Normal... He's ...,5.7,8.387519,Just when George Banks has recovered from his ...

In [25]:
df['tags'][1]

"When siblings Judy and Peter discover an enchanted board game that opens the door to a magical world, they unwittingly invite Alan -- an adult who's been trapped inside the game for 26 years -- into their living room. Alan's only hope for freedom is to finish the game, which proves risky as all three find themselves running from giant rhinoceroses, evil monkeys and other terrifying creatures. Adventure Fantasy Family Roll the dice and unleash the excitement!"

In [26]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import re

In [27]:
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...

True

In [28]:
stop_words=set(stopwords.words('english'))
lemmatizer=WordNetLemmatizer()

In [29]:
import re
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

# download once
# nltk.download('stopwords')
# nltk.download('wordnet')

stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

def preprocess_text(text):

    # lowercase
    text = str(text).lower()

    # remove punctuations
    text = re.sub(r'[^a-zA-Z\s]', '', text)

    # tokenize
    words = text.split()

    # remove stopwords
    words = [word for word in words if word not in stop_words]

    # lemmatization
    words = [lemmatizer.lemmatize(word) for word in words]

    return " ".join(words)

In [30]:
df['tags']=df['tags'].apply(preprocess_text)

In [31]:
df['tags'][1]

'sibling judy peter discover enchanted board game open door magical world unwittingly invite alan adult who trapped inside game year living room alans hope freedom finish game prof risky three find running giant rhinoceros evil monkey terrifying creature adventure fantasy family roll dice unleash excitement'

In [32]:
df=df.reset_index(drop=True)

In [33]:
indices=pd.Series(df.index,index=df['title']).drop_duplicates()

In [34]:
indices

title
Toy Story                          0
Jumanji                            1
Grumpier Old Men                   2
Waiting to Exhale                  3
Father of the Bride Part II        4
                               ...
Subdue                         45442
Century of Birthing            45443
Betrayal                       45444
Satan Triumphant               45445
Queerama                       45446
Length: 45447, dtype: int64

In [35]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(
    max_features=50000,
    ngram_range=(1, 2),
    stop_words='english'
)

tfidf_matrix = tfidf.fit_transform(df['tags'])

tfidf_matrix

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 1548114 stored elements and shape (45447, 50000)>

In [36]:
df['tags']

0        led woody andys toy live happily room andys bi...
1        sibling judy peter discover enchanted board ga...
2        family wedding reignites ancient feud nextdoor...
3        cheated mistreated stepped woman holding breat...
4        george bank recovered daughter wedding receive...
                               ...
45442    rising falling man woman drama family rising f...
45443    artist struggle finish work storyline cult pla...
45444    one hit go wrong professional assassin end sui...
45445    small town live two brother one minister one h...
45446    year decriminalisation homosexuality uk direct...
Name: tags, Length: 45447, dtype: object

In [37]:
tfidf_matrix = tfidf.fit_transform(df['overview'])

In [38]:
from sklearn.metrics.pairwise import cosine_similarity

def recommend(title, n=10):

    if title not in indices:
        return ["Movie not found"]

    idx = indices[title]

    # compare one movie with all movies
    sim_score = cosine_similarity(
        tfidf_matrix[idx],
        tfidf_matrix
    ).flatten()

    # sort similarity scores
    similar_idx = sim_score.argsort()[::-1][1:n+1]

    return df['title'].iloc[similar_idx]

In [39]:
recommend('The Dark Knight Rises')

150                                         Batman Forever
585                                                 Batman
12478                                      The Dark Knight
1328                                        Batman Returns
15507                           Batman: Under the Red Hood
9228                    Batman Beyond: Return of the Joker
35965                                    Batman: Bad Blood
21186    Batman Unmasked: The Psychology of the Dark Kn...
18030                                     Batman: Year One
11750                                            Slow Burn
Name: title, dtype: object

In [40]:
recommend('The Godfather')

44011    The Godfather Trilogy: 1972-1990
1178               The Godfather: Part II
31957                    Honor Thy Father
29                         Shanghai Triad
11294                    Household Saints
18317                     The Outside Man
23115                          Blood Ties
13174                        I Am the Law
16325               New York Confidential
16246             The Outlaw and His Wife
Name: title, dtype: object

In [41]:
def recommend_by_genre(genre, n=10):

    # filter genre safely
    genre_movies = df[
        df["genres"].str.lower().str.contains(genre.lower(), na=False)
    ]

    if genre_movies.empty:
        return ["Genre not found"]

    # sort using Netflix-style score
    genre_movies = genre_movies.sort_values(
        "score", ascending=False
    )

    return genre_movies["title"].head(n)

In [42]:
print(df.dtypes)

title            object
overview         object
genres           object
tagline          object
vote_average    float64
popularity       object
tags             object
dtype: object

In [43]:
df = df.dropna(subset=["vote_average", "popularity"])

In [45]:
# convert to numeric
df["vote_average"] = pd.to_numeric(df["vote_average"], errors="coerce")
df["popularity"] = pd.to_numeric(df["popularity"], errors="coerce")

# remove invalid rows
df = df.dropna(subset=["vote_average", "popularity"])

# create score
df["score"] = (
    df["vote_average"] * 0.7 +
    df["popularity"] * 0.3
)

In [46]:
df.dtypes

title            object
overview         object
genres           object
tagline          object
vote_average    float64
popularity      float64
tags             object
score           float64
dtype: object

In [47]:
recommend_by_genre("Comedy")
recommend_by_genre("Adventure")
recommend_by_genre("Family")

30684                                     Minions
42203                        Beauty and the Beast
24444                                  Big Hero 6
43267    Captain Underpants: The First Epic Movie
5480                                Spirited Away
30385     Fantastic Beasts and Where to Find Them
4765     Harry Potter and the Philosopher's Stone
43990                             Despicable Me 3
45120                             The Emoji Movie
5677      Harry Potter and the Chamber of Secrets
Name: title, dtype: object

In [48]:
def recommend(query, n=10):

    query = query.strip()

    # 1️⃣ If movie title exists → cosine similarity
    if query in indices:
        return recommend_movie(query, n)

    # 2️⃣ If genre exists → genre recommendation
    if df["genres"].str.lower().str.contains(query.lower(), na=False).any():
        return recommend_by_genre(query, n)

    # 3️⃣ Not found
    return ["Movie or Genre not found"]

In [49]:
import pandas as pd

# convert to numeric (safe)
df["vote_average"] = pd.to_numeric(df["vote_average"], errors="coerce")
df["popularity"] = pd.to_numeric(df["popularity"], errors="coerce")

df = df.dropna(subset=["vote_average","popularity"])

# Netflix-style score
df["score"] = (
    df["vote_average"] * 0.7 +
    df["popularity"] * 0.3
)

In [50]:
from sklearn.metrics.pairwise import cosine_similarity

def recommend_movie(title, n=10):

    if title not in indices:
        return ["Movie not found"]

    idx = indices[title]

    sim_score = cosine_similarity(
        tfidf_matrix[idx],
        tfidf_matrix
    ).flatten()

    similar_idx = sim_score.argsort()[::-1][1:n+1]

    return df["title"].iloc[similar_idx]

In [51]:
def recommend_by_genre(genre, n=10):

    genre_movies = df[
        df["genres"].str.lower().str.contains(genre.lower(), na=False)
    ]

    if genre_movies.empty:
        return ["Genre not found"]

    genre_movies = genre_movies.sort_values(
        "score", ascending=False
    )

    return genre_movies["title"].head(n)

In [52]:
def recommend(query, n=10):

    query = query.strip()

    # 1️⃣ If movie title exists → cosine similarity
    if query in indices:
        return recommend_movie(query, n)

    # 2️⃣ If genre exists → genre recommendation
    if df["genres"].str.lower().str.contains(query.lower(), na=False).any():
        return recommend_by_genre(query, n)

    # 3️⃣ Not found
    return ["Movie or Genre not found"]

In [53]:
recommend("Toy Story")   # movie similarity
recommend("Comedy")      # genre-based
recommend("Adventure")   # genre-based
recommend("xyz")         # not found

['Movie or Genre not found']

In [54]:
recommend("The Dark Knight Rises")

150                                         Batman Forever
585                                                 Batman
12478                                      The Dark Knight
1328                                        Batman Returns
15507                           Batman: Under the Red Hood
9228                    Batman Beyond: Return of the Joker
35965                                    Batman: Bad Blood
21186    Batman Unmasked: The Psychology of the Dark Kn...
18030                                     Batman: Year One
11750                                            Slow Burn
Name: title, dtype: object

In [55]:
recommend('comedy')

30684                                             Minions
24444                                          Big Hero 6
26552                                            Deadpool
26554                      Guardians of the Galaxy Vol. 2
26548    Pirates of the Caribbean: Dead Men Tell No Tales
43267            Captain Underpants: The First Epic Movie
351                                          Forrest Gump
2210                                    Life Is Beautiful
30674                                               Ted 2
10306                         Dilwale Dulhania Le Jayenge
Name: title, dtype: object

In [56]:
!pip install rapidfuzz

Collecting rapidfuzz
  Downloading rapidfuzz-3.14.3-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (12 kB)
Downloading rapidfuzz-3.14.3-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (3.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 39.2 MB/s eta 0:00:00
Installing collected packages: rapidfuzz
Successfully installed rapidfuzz-3.14.3

In [57]:
from rapidfuzz import process

In [58]:
def find_closest_match(query):

    # movie titles list
    movie_titles = df["title"].tolist()

    # genres list
    all_genres = set(" ".join(df["genres"].fillna("")).lower().split())

    # best movie match
    movie_match = process.extractOne(query, movie_titles)

    # best genre match
    genre_match = process.extractOne(query.lower(), list(all_genres))

    return movie_match, genre_match

In [59]:
def recommend_smart(query, n=10):

    query = query.strip()

    # lowercase movie matching
    lower_titles = df["title"].str.lower()

    # 1️⃣ Exact movie match (case insensitive)
    if query.lower() in lower_titles.values:
        real_title = df[df["title"].str.lower()==query.lower()]["title"].iloc[0]
        return recommend_movie(real_title, n)

    # 2️⃣ Exact genre match
    if df["genres"].str.lower().str.contains(query.lower(), na=False).any():
        return recommend_by_genre(query, n)

    # 3️⃣ Fuzzy matching (typo correction)
    movie_match, genre_match = find_closest_match(query)

    # similarity score check
    if movie_match and movie_match[1] > 70:
        return recommend_movie(movie_match[0], n)

    if genre_match and genre_match[1] > 70:
        return recommend_by_genre(genre_match[0], n)

    return ["Movie or Genre not found"]

In [60]:
recommend_smart("toy stor")

27709                                Finsterworld
22259                      Hava Nagila: The Movie
35972                  I'm a Stranger Here Myself
44872                                  Savageland
18031                     America before Columbus
45030                    Kerosene Salesman's Wife
17921                             Brothers at War
20753                            The Prodigal Son
18323                        The Painting Sellers
41393    Classic Albums: Black Sabbath - Paranoid
Name: title, dtype: object

In [61]:
recommend_smart("toy story")

15344                                     Toy Story 3
2996                                      Toy Story 2
10298                          The 40 Year Old Virgin
24512                                       Small Fry
23832                     Andy Hardy's Blonde Trouble
29189                                      Hot Splash
43408                Andy Kaufman Plays Carnegie Hall
42702    Andy Peters: Exclamation Mark Question Point
8326                                        The Champ
40242                                   Wabash Avenue
Name: title, dtype: object

In [62]:
# ===============================
# 7️⃣ FUZZY MOVIE MATCH (TYPO FIX)
# ===============================
def get_best_movie_match(query):

    movie_titles = df["title"].str.lower().tolist()

    match = process.extractOne(
        query.lower(),
        movie_titles,
        score_cutoff=65   # stable threshold
    )

    if match:
        real_title = df[
            df["title"].str.lower() == match[0]
        ]["title"].iloc[0]

        return real_title

    return None


# ===============================
# 8️⃣ FINAL SMART RECOMMENDER
# ===============================
def recommend(query, n=10):

    query = query.strip()

    # 1️⃣ Case-insensitive exact movie match
    lower_titles = df["title"].str.lower()

    if query.lower() in lower_titles.values:
        real_title = df[
            df["title"].str.lower() == query.lower()
        ]["title"].iloc[0]

        print("Showing results for movie:", real_title)
        return recommend_movie(real_title, n)

    # 2️⃣ Genre match
    if df["genres"].str.lower().str.contains(query.lower(), na=False).any():
        print("Showing top movies in genre:", query)
        return recommend_by_genre(query, n)

    # 3️⃣ Fuzzy movie match (typo correction)
    best_movie = get_best_movie_match(query)

    if best_movie:
        print("Showing results for:", best_movie)
        return recommend_movie(best_movie, n)

    return ["Movie or Genre not found"]

In [63]:
recommend("toy stor")

Showing results for: Toy Story

15344                                     Toy Story 3
2996                                      Toy Story 2
10298                          The 40 Year Old Virgin
24512                                       Small Fry
23832                     Andy Hardy's Blonde Trouble
29189                                      Hot Splash
43408                Andy Kaufman Plays Carnegie Hall
42702    Andy Peters: Exclamation Mark Question Point
8326                                        The Champ
40242                                   Wabash Avenue
Name: title, dtype: object

In [64]:
recommend("Toy Story")

Showing results for movie: Toy Story

15344                                     Toy Story 3
2996                                      Toy Story 2
10298                          The 40 Year Old Virgin
24512                                       Small Fry
23832                     Andy Hardy's Blonde Trouble
29189                                      Hot Splash
43408                Andy Kaufman Plays Carnegie Hall
42702    Andy Peters: Exclamation Mark Question Point
8326                                        The Champ
40242                                   Wabash Avenue
Name: title, dtype: object

In [65]:
recommend("Adventure")

Showing results for movie: Adventure

27373        Slap Shot 3: The Junior League
42025          How to Win the US Presidency
44519                           The Old Man
10747                              Bandidas
11830    The Librarian: Quest for the Spear
27997                   The Last Gladiators
4092                       The Longest Yard
17914              The Toast of New Orleans
19183                       2010: Moby Dick
18576                          Bombay Beach
Name: title, dtype: object

In [71]:
import pickle

# Save tfidf matrix
pickle.dump(tfidf_matrix, open("tfidf_matrix.pkl", "wb"))

# Save indices
pickle.dump(indices, open("indices.pkl", "wb"))

# Save tfidf vectorizer
pickle.dump(tfidf, open("tfidf.pkl", "wb"))

# Save dataframe
df.to_pickle("df.pkl")

In [73]:
import requests

api_key = "b8774aec"

movie = "Toy Story"

url = f"http://www.omdbapi.com/?t={movie}&apikey={api_key}"

response = requests.get(url)
data = response.json()

print(data["Poster"])

https://m.media-amazon.com/images/M/MV5BZTA3OWVjOWItNjE1NS00NzZiLWE1MjgtZDZhMWI1ZTlkNzYwXkEyXkFqcGc@._V1_SX300.jpg